/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author gdars
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jReservaciones = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jClientes = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jListaHabitaciones = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jNotificacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 50)); // NOI18N
        jLabel1.setText("BIENVENIDO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jMenu2.setText("Archivo ");

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jMenu2.add(jSalir);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reservas");

        jReservaciones.setText("Reservaciones");
        jReservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReservacionesActionPerformed(evt);
            }
        });
        jMenu3.add(jReservaciones);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Clientes");

        jClientes.setText("Clientes");
        jClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientesActionPerformed(evt);
            }
        });
        jMenu4.add(jClientes);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Habitaciones");

        jListaHabitaciones.setText("Lista Reservas");
        jListaHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListaHabitacionesActionPerformed(evt);
            }
        });
        jMenu5.add(jListaHabitaciones);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Notificaciones");

        jNotificacion.setText("Reservas");
        jNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNotificacionActionPerformed(evt);
            }
        });
        jMenu6.add(jNotificacion);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas salir?","CUIDADO" ,JOptionPane.YES_NO_OPTION);
        if(dialogButton == JOptionPane.YES_OPTION){
            System.exit(0);
        } else {
            remove(dialogButton);
        }
    }//GEN-LAST:event_jSalirActionPerformed

    private void jReservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReservacionesActionPerformed
        // TODO add your handling code here:
        FrmReservacion frmr = new FrmReservacion();
        frmr.setVisible(true);
        this.setVisible(false);
        

    }//GEN-LAST:event_jReservacionesActionPerformed

    private void jClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientesActionPerformed
        // TODO add your handling code here:

        FrmClientes cl = new FrmClientes();
        cl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jClientesActionPerformed

    private void jListaHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListaHabitacionesActionPerformed
        FrmSPORC sporc = new FrmSPORC();
        sporc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jListaHabitacionesActionPerformed

    private void jNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNotificacionActionPerformed
        FrmAlertas alertas = new FrmAlertas();
        alertas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jNotificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jListaHabitaciones;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jNotificacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jReservaciones;
    private javax.swing.JMenuItem jSalir;
    // End of variables declaration//GEN-END:variables
}
